# Render.com deployment configuration
version: 1

services:
  - type: web
    name: murfai-conversational-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
